{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goclaw.fullname" . }}
  labels:
    {{- include "goclaw.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  GOCLAW_GATEWAY_TOKEN: {{ .Values.config.gatewayToken | default (randAlphaNum 64) | quote }}
  GOCLAW_ENCRYPTION_KEY: {{ .Values.config.encryptionKey | default (randAlphaNum 64) | quote }}
  {{- if .Values.db.enabled }}
  POSTGRES_PASSWORD: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}
